language: python
python:
  - "3.7"

if: branch = main

cache:
  directories:
    - $HOME/.cache/pip

install:
  - echo "========== INSTALL =========="
  - pip install -r requirements.txt
#  - pip install flake8

script: 
  - echo "========== TESTING =========="
  - python -m unittest test/test_*.py

before_deploy: echo "========== DEPLOYING =========="

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    username: "__token__"
    password:
          secure: "VC6vvzTxt3v1Cb3CoVgUg0u+FSRvohFyNPI8jDn38hwe9VC96eBLV/3QaTYQ/3CwUo/j6RarszsNKaEHY7x25NPq8UsMZEcfSh0fDY6dKSs/aat0d8UwEL3ZVZfp5y8KTf7F1/KQdD+RdfGNYRF8EHFCYQy2/w8XyaEfoTeWuFlSRvJriSK5OWfcgEbr62Es55hnINN9Hb1jY1zUlqm7o7EBlMf6kKjs5aPrONQ0IW1daS1BvZK2pskZRjQFprMJSS/WgDYah55VEwc2wbjjGsqw7LmEMBAdYeZtdLKUfYdf5n+Ic6cy2hmjBd3U2ip8JVjayHyuCJuZtaHEmR1xdnt2mdFiMHNqzG8TZlD7LXno1jJfuHNd8ZbD/XRu1XZYeZ00tvaVBbTAOj5PvYa6xm8vrg/PoZM2UIhaAmApNXXFhAkIWHqxv5KYqlSKytOlOcaDIjg9o3yyUcHAJeN46IlYYekOno1kR+3QkV0jysoAey2e05yxfDf1/ONKdNhTDRba8UtLCbpWnHKG7Vc0156AevIp6ChNgQMNiPi0+OvX7tVkVCN82/Dj/qkM8Q4O0wP0l8WAMCWkSHNuvfeiOGH8KO/UjLWMM8sNKy/zrQgyHne14KrMzvIYSH5xuBMcfRvdXSXeZwG/skaDJp8DFiSSKlqbcMXM/c10UbVzLrA="
    on:
      branch: master
      tags: true
  
  - provider: releases
    api_key:
      secure: "T3AMFyHhbftp+dvCvX1Pa6YWE50Lv8bAUHzPC2IrPLSoTyE73bFdR7TX+ulTLQecw5CsptKk2rBeGzFynBkdc2rnq0mKteaoCJKDDfRVbBqWUrP9L6zfuTubWnfArCOMrAZIcr2KO4qbUSqv7w2YWsJF4XKhozJXzlNQSXTq/Jlvh09V9hChq13xdUP5VLb8YtpbRbshvyBtK/4dQ1F1lDmUeviDRGe04Z68qd8nvHOwvxkOOnKDF47wGWlYpmvoSPmk1Ufwi1iRI0vHRdP19KgLEdCe3yPOWLBVkS5iiv7ls709iVteB6tmwNiQpBg1nU1BUVMlT9vFH5RS1SU4ystTcGMMG8G6NhgDe3yW89lnCtJrRwj85PvX3iTBzQqrLEFLywDnfX6UDquycWduM1jsTc8HHJqNmCgxy4UKFs6pdDWeqx2waVkvNEYQ4D7Sgjj0e09GCJ8afhq4vtTIfag1Gy2RL/05f6pE3wSXGPc7D8X5AjXsmbEH9Azb3NqfXnQ/HQ1PXJXG6xmhhWkUNl3LZTOocFuKhUseeVIvPX1ZQrpLD2bqQNDfVEhVrjk3F6x4b904Rb0Jk2ti3gMNsxRt9OKbOEDoXmNA7+9JIIt65OXg5NAOYLbfmFoa888ErMT7g6b7GeWJIt/GyyWHRrb9U6mMWWmFP0vepThwV7M="
    file_glob: true
    file: firefly*.whl
    skip_cleanup: true
    on:
      branch: master
      tags: true

notifications:
  email:
    on_success: never
    on_failure: always

# Notify discord
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
