language: python
python:
  - "3.7"

if: tag IS present

cache:
  directories:
    - $HOME/.cache/pip

install:
  - echo "========== INSTALL =========="
  - pip install -r requirements.txt
#  - pip install flake8

script: 
  - echo "========== TESTING =========="
  - python -m unittest test/test_*.py

before_deploy: echo "========== DEPLOYING =========="

deploy:
  - provider: pypi
    edge: true
    remove_build_dir: false
    distributions: "sdist bdist_wheel"
    username: "__token__"
    password:
          secure: "VC6vvzTxt3v1Cb3CoVgUg0u+FSRvohFyNPI8jDn38hwe9VC96eBLV/3QaTYQ/3CwUo/j6RarszsNKaEHY7x25NPq8UsMZEcfSh0fDY6dKSs/aat0d8UwEL3ZVZfp5y8KTf7F1/KQdD+RdfGNYRF8EHFCYQy2/w8XyaEfoTeWuFlSRvJriSK5OWfcgEbr62Es55hnINN9Hb1jY1zUlqm7o7EBlMf6kKjs5aPrONQ0IW1daS1BvZK2pskZRjQFprMJSS/WgDYah55VEwc2wbjjGsqw7LmEMBAdYeZtdLKUfYdf5n+Ic6cy2hmjBd3U2ip8JVjayHyuCJuZtaHEmR1xdnt2mdFiMHNqzG8TZlD7LXno1jJfuHNd8ZbD/XRu1XZYeZ00tvaVBbTAOj5PvYa6xm8vrg/PoZM2UIhaAmApNXXFhAkIWHqxv5KYqlSKytOlOcaDIjg9o3yyUcHAJeN46IlYYekOno1kR+3QkV0jysoAey2e05yxfDf1/ONKdNhTDRba8UtLCbpWnHKG7Vc0156AevIp6ChNgQMNiPi0+OvX7tVkVCN82/Dj/qkM8Q4O0wP0l8WAMCWkSHNuvfeiOGH8KO/UjLWMM8sNKy/zrQgyHne14KrMzvIYSH5xuBMcfRvdXSXeZwG/skaDJp8DFiSSKlqbcMXM/c10UbVzLrA="
    on:
      branch: main
      tags: true
  
  - provider: releases
    api_key:
      secure: "GwI9rJlZieHsjHt3yUYR4j5F+kKflY7SVcHnDYHy2OqR4nzhz7BqPLSAxwoJKxJIzV5VdPMfG6N3MrIrGNdUraTIyeZAQlWajypPpGBm0YcJLZEgRVMDIsrzmUuUap4bBlnNB7BBXfy7Aapa2qP4Pt6tv1h6Cx6bn/KliAwn8MxYEzgCg4Fp8V/6WMuyDbu0VBfvQ9JqceBC1kvyrIu58/LurIZ+hzlStvmZ9DB1nzyXPT7OOkvOZ8zhAf0n6ySE14sKb8oELQUl6GoFhYmTVdwL0H9oWfrS1fj5xLDaFt7U0SDxAvrLvkYZOVyHiTwBaJr5M7D9Z0z53CLEmZ0PpH1zHY467D6XTF9c0C4l+UV22AvenNkoLCad6Fq3lpFZQwrDrDByvXoKmHmJogmodDgZbH9wDIq73dEHt28I4I1v1jYQyouYX5CH1VGd/KfTNzAd03bzS4SfoCvGLeZCHfDpWra//pXdDFggO7VuprusiJZVmOq5TFnAnxVOPRlFzIwIgX4J3JQMF4tVHpdVHt/Bonn3NIQUbvQYbkymAZ4Uz3sur9n2lvj+kAvkxuta+nRaL3h/RVpa2dW4pq4CiAELbk0AmivyvvSucnnJzwSv0Hh80upvK/IDcrv63Nc8bo2yrOPetXUD8ML+ctFqHt/FsgKcXAWFNxgVWYBMQqY="
    file_glob: true
    file: dist/firefly*
    skip_cleanup: true
    on:
      branch: main
      tags: true

notifications:
  email:
    on_success: never
    on_failure: always

# Notify discord
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
