version: '3.3'

services:
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly-dev
    environment:
      - APP_KEY=3tPZNJV1gI90B5a5S3k58o7RV16ZlHRX
      - DB_HOST=mariadb-dev
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=firefly
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb-dev
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=firefly
      - MYSQL_DATABASE=firefly
